# This file contains values from Cookiecutter

default_context:
  project_name: "sftui"
  project_description: "TUI for interacting with the ShareFile API"
  organization: "Xtal Systems"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "kriipke"
  email: "mail@kriipke.io"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
